### ISSUE TITLE
Sum operator is not implemented

### ISSUE THREAD

**Issue by yanbraslavsky-home24** [aNNiMON/Lightweight-Stream-API#10]
First of all I love this port , it is very useful. 
Thank you for that !

There are a lot more operators for stream in Java 8 stream API , one of the most usefull is the "sum" 
https://docs.oracle.com/javase/8/docs/api/java/util/stream/IntStream.html#sum--

Any chance you will implement it any time soon ? 
Is there a road map for your port anywhere ?

**Comment by aNNiMON** [comment]
@yanbraslavsky-home24 thank you for the feedback. I did not add these methods, because they can be easily implemented by existing library functions. Otherwise it would not be a *lightweight* library :grinning: 

```java
int sum = Stream.ofRange(1, 9).reduce(0, new BinaryOperator<Integer>() {
    @Override
    public Integer apply(Integer value1, Integer value2) {
        return value1 + value2;
    }
});
```

**Comment by yanbraslavsky-home24** [comment]
That is exactly how I have implemented it.Just for my convinience I wanted them to be in the library. Maybe I'll fork it then ;)

**Comment by aNNiMON** [comment]
@yanbraslavsky-home24 no, it's hard to implement parallel processing with Iterators. Java 8 uses Spliterators for this.
