### ISSUE TITLE
Make sure iterators do not keep references to previous objects

### ISSUE THREAD

**Issue by dalewking** [aNNiMON/Lightweight-Stream-API#100]
In my issue about adding takeUntil I noted thar your implementation did not include my code for setting next to null to avoid leaking memory. But looking at some of the other methods have similar problems.

It occurs to me that perhaps this could be handled at the LsaExtIterator level. After the call to nextIteration you can just check if hasNext is false and if so set next to null.

**Comment by aNNiMON** [comment]
After looking to `LsaExtIterator` I found another error related to iterators. Both issues were fixed.
Thanks for pointing this out.
