### ISSUE TITLE
Add indexed methods to Stream to simplify using indexes

### ISSUE THREAD

**Issue by dalewking** [aNNiMON/Lightweight-Stream-API#103]
I have these calls in a stream because I need to map a value based on the index and the value:

            .indexed()
            .map(p -> getPredecessorForRow(p.getFirst()).pathTo(p.getFirst(), p.getSecond()))

which is very cumbersome having to deal with IntPair and not very readable.

 If you look at [Sequence in Kotlin](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.sequences/-sequence/index.html) (which is the equivalent of a Stream) it has Indexed versions for filter, map, forEach, and reduce (aka fold). It would be nice to have these in this library.

These would depend on some new interfaces that take the index as a parameter along with the value.

With a mapIndexed function the above becomes:

            .mapIndexed((i, value) -> getPredecessorForRow(i).pathTo(i, value))

FYI, while looking at [Sequence in Kotlin](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.sequences/-sequence/index.html) feel free to look for other functions that would be good candidates there for inclusion.

**Comment by aNNiMON** [comment]
To properly implement this feature I need to remove `final` modifier from `Stream` class, create class `IndexedStream` which extends `Stream<IntPair<T>>`, modify `indexed` methods signature, add base interface for both classes and make some kind of magic with generics. 

```java
Stream.of(...) // Stream<T>
        .indexed()  // IndexedStream<T>
        .filter(p -> ...) // Stream<T>
        .mapIndexed((i, value) -> ...) // no method mapIndexed in Stream
```

Or just copy-paste all methods to `IndexedStream` with changing signature :smile: 

Instead, I suggest to use custom operators. Here is an example:

```java
public interface IntObjFunction<T, R> {
    R apply(int value1, T value2);
}

public static <T, R> Function<Stream<IntPair<T>>, Stream<IntPair<R>>> mapIndexed(
        final IntObjFunction<? super T, IntPair<R>> mapper) {
    return new Function<Stream<IntPair<T>>, Stream<IntPair<R>>>() {

        @Override
        public Stream<IntPair<R>> apply(Stream<IntPair<T>> stream) {
            final Iterator<? extends IntPair<T>> iterator = stream.iterator();
            return Stream.of(new LsaIterator<IntPair<R>>() {

                @Override
                public IntPair<R> nextIteration() {
                    final IntPair<T> pair = iterator.next();
                    return mapper.apply(pair.getFirst(), pair.getSecond());
                }

                @Override
                public boolean hasNext() {
                    return iterator.hasNext();
                }
            });
        }
    };
}

Stream.of(0.1, 0.2, 0.3)
        .indexed()
        .custom(mapIndexed( (i, value) -> new IntPair<Integer>(i, (int) (i / value)) ))
        .map(p -> ...)
```

**Comment by dalewking** [comment]
Think you misunderstood the proposal. I was talking about methods on Stream itself. 

I will supply an example later tonight.

**Comment by aNNiMON** [comment]
It is impossible to specify that the method should be applied only for `T == IntPair`.

I can create, for example, `mapIndex`, that can count and map elements:

```java
Stream mapIndex(IntObjFunction<T, IntPair<R>> mapper) {
    ...
    int index;
  
    @Override
    public IntPair<R> nextIteration() {
        return mapper.apply(index++, iterator.next());
    }
}
```

It's okay. But after calling `indexed()` `mapIndex` will use `(int index, IntPair<T> value)`, not `(int index, T value)`.

**Comment by dalewking** [comment]
You mistakenly thought I meant you would call indexed first. Not at all, no call to indexed and no IntPair instances ever created.

 The idea is like this. Say I wanted only the even indexed items:

      Stream.of("a", "e", "i", "o", "u")
            .filterIndexed((index, item) -> index %2 == 0)

would be a stream of "a", "i", "u"

The parameter to filterIndexed would be a new interface:

public interface IndexedPredicate<T>
{
     boolean test(int index, T value);
}

Similarly the parameter to mapIndexed would be:

    public interface IndexedFunction<T, R>
    {
        R apply(int index, T t);
    }

forEachIndexed would have a parameter of:

    public interface Consumer<T>
    {
        void accept(int index, T t);
    }

foldIndexed (and you should add a scanIndexed) would only be for the version with the initial seed and take an interface of:

    public interface IndexedBiFunction<T, U, R>
    {
        R apply(T value1, int index, U value2);
    }

Does that make it clearer? The only difference from the non-indexed version is that you have an additional int parameter to the interfaces and the iterator tracks the index and feeds it to the interface.

**Comment by aNNiMON** [comment]
Thanks for an explanation. As for me, it would be nice to configure index (start value and step) after `indexed` call and use index supplied by IntPair, rather than create counter on each -Indexed function. Since it difficult in my version, I agree with your point.

**Comment by dalewking** [comment]
That functionality could be provided by utility wrapper functions in each interface to translate the 0 based index to whatever you want prior to passing it to the function being wrapped.

**Comment by aNNiMON** [comment]
Or just with simple data class `Index {int from, int step}`.

Methods:

```java
mapIndexed(Function) {
    return mapIndexed(DEFAULT_INDEX, function)
}

mapIndexed(Index, Function) { .. }

// etc
```

**Comment by dalewking** [comment]
mapIndexed(int start, int step, Function) { .. }

Would make more sense, but I don't see much use for this functionality. If you did need it makes more sense to let the user do it in the function they pass.

**Comment by dalewking** [comment]
Might make sense to also do takeWhileIndexed and takeUntilIndexed, which uses the same IndexedPredicate as filterIndexed.
