### ISSUE TITLE
Additional implementations for Function.Util.safe

### ISSUE THREAD

**Issue by PromanSEW** [aNNiMON/Lightweight-Stream-API#106]
Where are implementations for IntFunction, LongFunction and DoubleFunction?
Example for IntFunction:
```java
public static <T, R> IntFunction<T, R> safe(
                final ThrowableFunction<? super T, ? extends R, Throwable> throwableFunction,
                final R resultIfFailed) {
	return new IntFunction<R>() {
		@Override
		public R apply(int value) {
			try {
				return throwableFunction.apply(value);
			} catch (Throwable throwable) {
				return resultIfFailed;
			}
		}
	};
}
```
Will you add them?

**Comment by aNNiMON** [comment]
Okay. But it will be `ThrowableIntFunction`, `ThrowableLongFunction` etc to avoid unnecessary boxing.

**Comment by PromanSEW** [comment]
I create this issue because I wanted to do ``mapToObj`` for ``IntStream`` with mapper throws ``JSONException``, but I had to create this helper method, so LSA does not contain it for ``Stream`` of primitives
