### ISSUE TITLE
Issue with filter + mapToObj

### ISSUE THREAD

**Issue by RomainPiel** [aNNiMON/Lightweight-Stream-API#108]
We're having issues with `filter` + `mapToObj`. This test:
```java
    @Test public void testStream() {
        List<Integer> items = newArrayList(0, 1, 2, 3, 4);

        List<String> list = range(0, items.size())
                .filter(i -> items.get(i) % 2 == 0)
                .mapToObj(String::valueOf)
                .collect(toList());

        assertThat(list).containsOnly("0", "2", "4");
    }
```

 is failing with the error.
```
java.util.NoSuchElementException
	at com.annimon.stream.LsaIterator.next(LsaIterator.java:20)
	at com.annimon.stream.Stream.collect(Stream.java:1596)
	at StreamTest.testStream(StreamTest.java:24)
```

It looks like a map on a filtered `IntStream` does some weird things, the output was never as expected with the few test cases I've played with.

**Comment by aNNiMON** [comment]
Thank you for feedback. The problem is wrong implementation of `filter` operator.

**Comment by RomainPiel** [comment]
@aNNiMON Wow that was quick! Thanks a lot! When are you planning to release this?

**Comment by aNNiMON** [comment]
@RomainPiel I plan to release v1.1.7 this week. You can wait for release or try current `master` branch with https://jitpack.io/

**Comment by RomainPiel** [comment]
@aNNiMON nice, thanks!
