### ISSUE TITLE
ComparatorCompat

### ISSUE THREAD

**Issue by BattleShipPark** [aNNiMON/Lightweight-Stream-API#109]
Hi,
You added ComparatorCompat recently. I appreciate it.

I have two questions about it.
First, (Even though it is very trival) I wondered why it is not Comparators because I felt Comparators is more natural.
Second, ComparatorCompat has only static methods and I can't use method chaining like comparing().reversed().thenComparing(). Could you provide ComparatorCompat as instantiate-able class? For example, I tried to inherit Comparator to declare Comparators like this:  https://github.com/BattleShipPark/Lightweight-Stream-API/commit/5de832821b25dcd549deae47cf720cfebf609d83

Thanks.

**Comment by aNNiMON** [comment]
Hi,

Thanks for raising such an important issue.

1. In Java 8 `Comparators` class marked as package private, so I preferred not to use it and chose `ComparatorCompat` as well as `RandomCompat`. I understand that `Comparators` looks much clearer and it is shorter by 5 characters... My bad.

2. There is `chain` method:

```java
ComparatorCompat
        .chain(comparator)
        .reversed()
        .thenComparing(...)
        .comparator();
```
See more (examples)[https://github.com/aNNiMON/Lightweight-Stream-API/blob/6d65ffaaa451f82516962eaab155c839c31b4ed7/stream/src/test/java/com/annimon/stream/ComparatorCompatTest.java#L200]

Your approach with abstract class is much better, I'll think about using it. The only problem is that `Comparators implements Comparator` is non-obvious. `Comparators` sounds like an utility class, not Comparator instance itself. And I have no idea how to call this class clearer.

**Comment by BattleShipPark** [comment]
Hi,
I missed Java 8 Comparators, and agree ComparatorCompat is a good alternative name. 

Then, what about `ComparatorCompat implements Comparator`? I am not sure such an inheritance makes no side effect ever but I think its approach is worth considering.

Thanks.

**Comment by aNNiMON** [comment]
Okay, I managed to make changes without loosing source compatibility.

@BattleShipPark, thank you for that suggestion.
