### ISSUE TITLE
Duplicated iterators

### ISSUE THREAD

**Issue by PromanSEW** [aNNiMON/Lightweight-Stream-API#111]
Why are these classes duplicated in root and `iterator` packages?

- `LazyIterator`
- `LsaExtIterator`
- `LsaIterator`
- `PrimitiveExtIterator`
- `PrimitiveIterator`

Please explain. Maybe I missed something in this code magic

**Comment by aNNiMON** [comment]
Look like Maven didn't want to update package. Thanks for reporting, that's problem in my build environment. I'll update libraries at Maven Central and Bintray soon.

**Comment by PromanSEW** [comment]
What do I have to do to download the correct library after fixing this problem?
Will you release new version, or I should delete Gradle cache at `~/.gradle/caches/modules-2/files-2.1/com.annimon/stream`?

**Comment by aNNiMON** [comment]
I have updated the library in Maven Central and jCenter. To force refresh dependencies, use `gradle build --refresh-dependencies` or delete cache files gradle cache dir.

I apologize for the inconvenience.

**Comment by PromanSEW** [comment]
Thanks. I have already downloaded updated library, and now everything is correct.
