### ISSUE TITLE
Replace @code with @link for class names in Javadoc

### ISSUE THREAD

**Issue by PromanSEW** [aNNiMON/Lightweight-Stream-API#113]
For example
```java
Creates a safe {@code DoubleConsumer}.
```
will be
```java
Creates a safe {@link DoubleConsumer}.
```
Then `DoubleConsumer` will be clickable for navigation

**Comment by aNNiMON** [comment]
Does the result in method signature is not clickable? [Example](http://static.javadoc.io/com.annimon/stream/1.1.7/com/annimon/stream/function/DoubleConsumer.Util.html#safe-com.annimon.stream.function.ThrowableDoubleConsumer-)

public static [DoubleConsumer](http://static.javadoc.io/com.annimon/stream/1.1.7/com/annimon/stream/function/DoubleConsumer.html) safe([ThrowableDoubleConsumer](http://static.javadoc.io/com.annimon/stream/1.1.7/com/annimon/stream/function/ThrowableDoubleConsumer.html)<[Throwable](http://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html?is-external=true)> throwableConsumer)

**Comment by PromanSEW** [comment]
You are right, it is clickable, of course. You can ignore my suggestion, so it is time-consuming and not really useful

**Comment by aNNiMON** [comment]
I think it is good practice to `link` a class that is not present in method signature in javadoc. I'll take this as a rule. Thanks.

**Comment by aNNiMON** [comment]
I looked at the javadoc comments and found a few candidates to replace `code` with `link`. In other cases, classes are present in method signature or in `@return` / `@throws` tags.
