### ISSUE TITLE
make Streams Closeable and support stream.onClose(Runnable)

### ISSUE THREAD

**Issue by frett** [aNNiMON/Lightweight-Stream-API#115]
The Java 8 Stream API supports specifying custom Stream cleanup logic after you are finished with the Stream by utilizing the AutoCloseable along with an `onClose(Runnable)` intermediate operation. https://docs.oracle.com/javase/8/docs/api/java/util/stream/BaseStream.html#onClose-java.lang.Runnable-

It would be nice to support this functionality in order to provide custom data source cleanup logic to run when a Stream has been consumed.

**Comment by aNNiMON** [comment]
I will try to implement this feature, thanks. But since `AutoCloseable` was introduced in Java 7, I can't implement this interface in Java 6 project.

**Comment by frett** [comment]
understandable for `AutoCloseable`, making it implement `Closeable` instead might be a good alternative.
