### ISSUE TITLE
Any plan to support parallel stream operators?

### ISSUE THREAD

**Issue by xingda920813** [aNNiMON/Lightweight-Stream-API#116]

**Comment by aNNiMON** [comment]
I don't plan parallel streams support in the near future. Parallel streams will increase the complexity and the size of the library. Most usage of the library is on Android, there is no enough large data to allow parallel stream to be better than sequential stream.

**Comment by xingda920813** [comment]
Understood. Thanks.

**Comment by maracuja-juice** [comment]
Okay. But parallelStreams are still twice as fast as normal streams.
