### ISSUE TITLE
Optional.filter bug?

### ISSUE THREAD

**Issue by PromanSEW** [aNNiMON/Lightweight-Stream-API#118]
Maybe I don't understand something, but
```java
return Optional.of((Quest) oin.readObject()).filter(q -> q.status != null).orElse(fromJSON(file));
```
is not the same that
```java
Quest q = (Quest) oin.readObject();
return q.status == null ? fromJSON(file) : q;
```
Because the first example causes recursion in my code, and the second does not. All other code is the same.
Where is my mistake?

**Comment by aNNiMON** [comment]
The problem is that  expression `fromJSON(file)` always evaluates in `orElse` call. You should use `orElseGet(Supplier other)`.

```java
return Optional.of((Quest) oin.readObject())
        .filter(q -> q.status != null)
        .orElseGet(() -> fromJSON(file));
```

**Comment by PromanSEW** [comment]
Thanks for explanation and example
