### ISSUE TITLE
Add OptionalBoolean

### ISSUE THREAD

**Issue by PromanSEW** [aNNiMON/Lightweight-Stream-API#119]
What about `OptionalBoolean` to avoid boxing?
I use `Optional<Boolean>` to indicate that server returns true or false, and `Optional.empty()` for request error, so this implementation can be useful in similar cases

**Comment by aNNiMON** [comment]
`OptionalBoolean` is overhead as for me. You can use `OptionalInt` and store 0 or 1.

**Comment by PromanSEW** [comment]
`boolean` is better for understanding in comparison with `int`.
Other example is reading configuration values with defaults of `true`, `false`.
If you think this feature is not really useful, you can close this issue.
I just suggest features that could be useful and which can be added to this library.
Thanks for it a lot!

**Comment by landawn** [comment]
@PromanSEW I think it's useful too. but you could implement it and add it to your toolkit :-)

**Comment by PromanSEW** [comment]
I would like to implement `OptionalBoolean`, but I did not find `BooleanConsumer`. `BooleanSupplier` exists, but `BooleanConsumer` does not. I think at least `BooleanConsumer` needed in your library
