### ISSUE TITLE
Cannot use Collectors.toMap()

### ISSUE THREAD

**Issue by IgorGanapolsky** [aNNiMON/Lightweight-Stream-API#12]
Hi,
I am trying to do something like this:
`Map<String, Station> map = mStationList.stream().collect(Collectors.toMap(Station::getKey,
                                    item -> item));`

But **toMap** method cannot be resolved.  Is this possible?

Thank you,
Igor

**Comment by aNNiMON** [comment]
@IgorGanapolsky thanks for feedback. I've implemented `toMap`, check out new changes.

**Comment by IgorGanapolsky** [comment]
Gracias.  But I've discovered that toMap() operation is still sequential,
just like iterating a List.  So I decided to use RXJava instead...
