### ISSUE TITLE
mapIndexed and filterIndexed for streams of primitives

### ISSUE THREAD

**Issue by PromanSEW** [aNNiMON/Lightweight-Stream-API#120]
Where are these methods?
Example of using filterIndexed:
```java
IntStream.of(0, 1, 5, 3, 2).filterIndexed((index, value) -> index == value)... // [0, 1, 3]
```
Or using `Stream.of(...).filterIndexed(...).mapToInt(Integer::intValue)` is enough?

**Comment by aNNiMON** [comment]
I'll think about adding this feature later. Thanks.

**Comment by landawn** [comment]
Please do not add!
There're a lot of methods: filterIndexed/mapIndexed/dropWhileIndexed/takeWhileIndexed/ added. Have you ever felt you're duplicating the API? Since there is already indexed() method.
I suggest add `Stream<IndexedInt> IntStream.indexed()`, `Stream<IndexedLong> LongStream.indexed()`, `Stream<IndexedDouble> DoubleStream.indexed()` if not yet, instead of adding bunch of duplicated methods. Here is a simple sample of IndexedInt:
```java
public final class IndexedInt {
      private final int index;
      private final int value;

      public int index() {
            return index;
      }

      public int value() {
            return value;
      }

      // TODO...
}

**Comment by aNNiMON** [comment]
@landawn, `IndexedInt` will cause a problem with memory since it uses objects instead of primitives.

Just compare:

```java
ToIntFunction<IndexedInt> mapper = (IndexedInt idx) -> idx.index() + idx.value();
int index = 0;
for (int value : input) {
   IndexedInt idx = new IndexedInt(index++, value);
   /* push to the new stream */mapper.applyAsInt(idx);
}
```

and

```java
IntBinaryOperator mapper = (int index, int value) -> index + value;
int index = 0;
for (int value : input) {
  /* push to the new stream */mapper.applyAsInt(index++, value);
}
```

Second option is much faster and uses less memory.

**Comment by landawn** [comment]
"_much slower or faster_" could be true, If that's all the application code or 100% of the application code is indexed() or the operations afterward indexed() consumer big percentage CPU usage. However, we know that's not true.  I did a quick performance test. there is no obvious performance improvement by the second code, or difference is only between 0.001 milliseconds and 0.002 milliseconds.
```java
@Test
public void test_indexed_perf() {
    final int[] input = Array.range(0, 1000);

    Profiler.run(1, 10000, 3, "indexed", () -> {
        ToIntFunction<IndexedInt> mapper = idx -> idx.index() + idx.value();
        int index = 0;
        long sum = 0;
        for (int value : input) {
            IndexedInt idx = IndexedInt.of(value, index++);
            sum += mapper.applyAsInt(idx);
        }
        assertEquals(999000, sum);
    }).printResult();

    Profiler.run(1, 10000, 3, "no indexed", () -> {
        IntBinaryOperator mapper = (index, value) -> index + value;
        int index = 0;
        long sum = 0;
        for (int value : input) {
            sum += mapper.applyAsInt(index++, value);
        }
        assertEquals(999000, sum);
    }).printResult();
}
```
We could say the second code is two/three times faster than the first code, but if the percentage of CPU usage consumed by these operations is < 1%. then we don't need/should not care the performance difference. After all, API is much more important that 0.1% performance improvement.

**Comment by aNNiMON** [comment]
Ok, I have repeated benchmark with JMH.

<details>
 <summary>Code</summary>

 ```java
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.MILLISECONDS)
@State(Scope.Benchmark)
public class IndexedBenchmarks {
    private static final int SIZE = 10000000;
    private int[] input;

    @Setup
    public void setup() {
        input = new int[SIZE];
        for (int i = 0; i < SIZE; i++) {
            if (i < SIZE / 2) {
                input[i] = i;
            } else {
                input[i] = i - SIZE;
            }
        }
    }

    @Benchmark
    public long indexedObject() {
        ToIntFunction<IndexedInt> mapper = idx -> idx.index() + idx.value();
        int index = 0;
        long sum = 0;
        for (int value : input) {
            IndexedInt idx = IndexedInt.of(value, index++);
            sum += mapper.applyAsInt(idx);
        }
        return sum;
    }

    @Benchmark
    public long indexedInts() {
        IntBinaryOperator mapper = (index, value) -> index + value;
        int index = 0;
        long sum = 0;
        for (int value : input) {
            sum += mapper.applyAsInt(index++, value);
        }
        return sum;
    }

    public static void main(String[] args) throws RunnerException {
        Options opt = new OptionsBuilder()
                .include(IndexedBenchmarks.class.getSimpleName())
                .warmupIterations(3)
                .measurementIterations(5)
                .forks(2)
                .build();

        new Runner(opt).run();
    }
}
```

</details>

Here is the result for array with 10000000 elements:

```
IndexedBenchmarks.indexedInts    avgt   10  10,418 ? 0,142  ms/op
IndexedBenchmarks.indexedObject  avgt   10  11,025 ? 0,134  ms/op
```

> API is much more important than 0.1% performance improvement

Totally agree with this point.


@PromanSEW, you can use `Stream` with `IndexedInt` as suggested by @landawn or you can create custom operator for `IntStream` for better performance.

**Comment by aNNiMON** [comment]
@PromanSEW, you can use `Stream` with `IndexedInt` as suggested by @landawn or you can create custom operator for `IntStream` for better performance.

**Comment by PromanSEW** [comment]
I agreed that these APIs will be redundant as of the same performance for solutions using existing methods.
Thanks.
