### ISSUE TITLE
IntStream.collect(Collectors.joining(", "))

### ISSUE THREAD

**Issue by PromanSEW** [aNNiMON/Lightweight-Stream-API#122]
I want to `collect` `IntStream` into `String` as comma separated values, and I did not found this method, which is available in `Stream` (`collect(Collectors.joining(", "))`)
`IntStream` has only `<R> R collect(Supplier<R> supplier, ObjIntConsumer<R> accumulator)` method
Why?

**Comment by PromanSEW** [comment]
I need to write ugly method for this operation:

**Comment by PromanSEW** [comment]
Implementations:

1. `IntStream.join(delimiter)`
2. `IntCollectors`, where:
   - `IntCollector joining(CharSequence delimiter)`
   - Then in `IntStream.collect(IntCollector collector)`

**Comment by aNNiMON** [comment]
Primitive streams in Java 8 doesn't support collector classes.

1. You can convert IntStream to Stream: `intstream..map(Object::toString).collect(Collectors.joining(", "))`

2. What's wrong with this solution:

```java
return IntStream.of(values).collect(StringBuilder::new, (sb, value) -> {
    if (sb.length() > 0) sb.append(", ");
    sb.append(value);
}).toString();
```

You can move lambda body to static method:

```java
return IntStream.of(values).collect(StringBuilder::new, Join::ints).toString();

public static void ints(StringBuilder sb, int value) {
    if (sb.length() > 0) sb.append(", ");
    sb.append(value);
}
```

3. You can create custom operator.

**Comment by landawn** [comment]
How about: `IntStream.of(values).boxed().collect(Collectors.joining(", "));`

**Comment by PromanSEW** [comment]
@aNNiMON thanks for solutions.
I hava already created more simple method for this operation because of using only once:
```java
public static String join(int[] values) {
	StringBuilder sb = new StringBuilder();
	for (int value : values) {
		if (sb.length() > 0) sb.append(", ");
		sb.append(value);
	}
	return sb.toString();
}
```
IntStream is really unnecessary here.
Features I proposed are redundant because of alternative good implementations by existing methods
