### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by landawn** [aNNiMON/Lightweight-Stream-API#124]
How about to return empty stream for `Stream<Map.Entry<K, V>> of(Map<K, V> map) ` is the input map/iterator/iterable/array is null or empty?

**Comment by aNNiMON** [comment]
I can't change the behavior of existing methods. I can create duplicate methods `ofNullable(Map)`, `ofNullable(Iterator)` etc instead, but wouldn't that be overhead?

**Comment by landawn** [comment]
it won't break other people's code because:
1, if map/iterator/... is not null, the expected behaviors/results are same.
2, if map/iterator/... is null, most likely there is no problem because most of people who do the null check, the code will be:

```java
if (map != null) {
    Stream.of(map).(/* doing something */);
}

// OR:
(map == null ? Stream.<K, V>empty() : Stream.of(map)).(/* doing something */)...;
```

Only when some one wrote below silly code: this is pretty rare and it should corrected.
```java
try {
      Stream.of(map /* is null */).(/* doing something */)...;
} catch (NullPointerException e) {
      // implement some business logic based on the NullPointerException.
}
```

So i think it should be ok if just add a warning in the release changes.

This change will reduce the NullPointerException in other people's code, and make this library more simple/easy to use, make other people's code more concise and robust.

**Comment by aNNiMON** [comment]
I understand, that for the library it would be great to reduce NPE and I can provide new methods to reduce errors, but I don't want to change the behavior of existing methods. How many users will read version changes and documentation after upgrade? Until I know for sure that nobody uses catching NPE and RuntimeException to prevent nulls for further using in the method, I can't change existing methods.

**Comment by landawn** [comment]
Well, 100% backward compatibility, if is not impossible, will be very difficult. I'm not aware of any library could keep 100% backward compatibility. Even the best one JDK, is not 100% backward compatibility. if the person doesn't read the changes/documentations before upgrade, it's not library's responsibility to keep the his/her application always run well after upgrade. 

These're only my opinions.

**Comment by aNNiMON** [comment]
I agree with your point. Maybe I'll change behavior in the future release with other incompatibilities.

I leave the issue open.

**Comment by aNNiMON** [comment]
See #139 
I think, it is better to have of/ofNullable methods separate.
