### ISSUE TITLE
Add findLast

### ISSUE THREAD

**Issue by landawn** [aNNiMON/Lightweight-Stream-API#125]
There is `findFirst`, not sure why there is no `findLast` or I missed it. I found it in JDK 8

**Comment by aNNiMON** [comment]
What is the purpose of this method? I didn't find it in JDK 8.
There is `findFirst` and `findAny`. [findAny](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#findAny--), according to the documentation, allows maximal performance in parallel operations.

**Comment by PromanSEW** [comment]
_Sample:_
Before:
```java
List<String> list = Stream.of(...).map(...).filter(...)....toList();
String last = list.get(list.size()-1);
```
After:
```java
String last = Stream.of(...).map(...).filter(...)....findLast();
```

**Comment by aNNiMON** [comment]
Ok, but `find*` methods means that element could be absent, so it's return type is `Optional`.

To get last element you can use `reduce` operator.

```java
Oprional<String>Stream.of(...).map(...).filter(...).reduce((v1, v2) -> v2)
```

Should I create alias `findLast() { return reduce(a,b) -> b; }`?

**Comment by PromanSEW** [comment]
@aNNiMON it is a good idea! It is more readable and informative as `reduce` and is opposite for `findFirst()`

**Comment by landawn** [comment]
>> _ I didn't find it in JDK 8._
Maybe I saw the findLast in somewhere else, and messed up with Java stream.

>> _What is the purpose of this method?_
There're a lot of scenarios, people need to get the first or last element. and getLast/last such methods are provided in libraries(e.g. Guava...). As you mentioned above, it can be done by `reduce`.  However it's not such straight forward or easy to read.

**Comment by usergoodvery** [comment]
Is there an intention to implement findAny()?

**Comment by aNNiMON** [comment]
@usergoodvery `findAny` operator is for parallel streams. In Java 8 Streams it returns the first element in the part of data of the current thread. Since LSA doesn't support parallel streams you can use `findFirst` method.
