### ISSUE TITLE
About Apache License

### ISSUE THREAD

**Issue by qingmei2** [aNNiMON/Lightweight-Stream-API#128]
Hello, we used your library in development, but when we added lisence, we found that you just initialized the Lisence file. In order to protect your interest, we use your library in the project, hope to get your permission, look forward to your reply!

**Comment by PromanSEW** [comment]
Also question: should I list your library in my project for users?

**Comment by aNNiMON** [comment]
Apache 2.0 license allows commercial and private usage. If you develop Android application just add licenses information as described in this article: [Open-Source Licenses and Android](https://www.bignerdranch.com/blog/open-source-licenses-and-android/).

Thank you for using Lightweight Stream API :+1:

**Comment by qingmei2** [comment]
Thank you for your prompt reply！
