### ISSUE TITLE
Custom operator for Optional

### ISSUE THREAD

**Issue by dr-projectiro** [aNNiMON/Lightweight-Stream-API#131]
How about to add Optional.custom() operator just as it is done for Stream?

Motivation1: 
I'm using Rx Observables in my Android project along with aNNiMON streams and optionals. I've got frequent situation where I map optional value to observable: if optional is present, then I map to real observable, if optional is not present, then I map to observable with single Optional.empty() value.

In other words, I'd like to have a kind of flatMap operator for Optional AND Observable. 
What happens if i'm using traditional Optional.map() operator:

> Optional<T> optional = init();
> optional.map(tValue -> createObservable(tValue)); // would be of type Optional<Observable<R>>, if createObservable(..) returns Observable<R>
> 

What I'd like to have with possible flatMap operator:

> Optional<T> optional = init();
> optional.flatMap(tValue -> createObservable(tValue)); // would be of type Observable<R>, if createObservable(..) returns Observable<R>
> 

I'm NOT proposing to add cross-library flatMap method here. I've just described the case convenient for me in personal.
What I'm proposing is to add Optional.custom() operator just like this is in Stream, so I can tailor my own mapper given to .custom() operator, which converts optional to desired observable.

Motivation2:
Optional can be interpreted as stream of size 0 or 1. Stream has already got .custom operator. It's natural to provide similar interfaces for the objects of the same nature.

**Comment by aNNiMON** [comment]
Thank you for an idea. I like it.
Should I also provide `custom` operator for primitive optional classes?

**Comment by PromanSEW** [comment]
@aNNiMON I think it will be logical to have similar methods for all `Optional` classes

**Comment by dr-projectiro** [comment]
Yep, I think it's good idea to have the operator for primitive optionals either. 

In general case it looks intuitive when primitive optional classes inherit (not obligatory like oop inheritance) methods and behavior of general optional class. 

Moreover,  integer stream already has '.custom()' operator, so with '.custom()' methods for primitive optionals this scheme looks really complete.
