### ISSUE TITLE
concat/merge/zip

### ISSUE THREAD

**Issue by landawn** [aNNiMON/Lightweight-Stream-API#133]
I saw there are two very useful methods:
```java
Stream<R> zip(Stream<? extends F> stream1, Stream<? extends S> stream2,
            final BiFunction<? super F, ? super S, ? extends R> combiner);

 Stream<R> zip(final Iterator<? extends F> iterator1,
            final Iterator<? extends S> iterator2,
            final BiFunction<? super F, ? super S, ? extends R> combiner);
```
And wondering why there is only one `concat`:
```java
Stream<T> concat(Stream<? extends T> stream1, Stream<? extends T> stream2);
```
Could we add one more `concat` for `Iterator`?
```java
Stream<T> concat(Iterator<? extends T> iterator1, Iterator<? extends T> iterator2);
```

And two `merge` methods:
```java
// Next element is appended from the element from Stream1 if `FIRST` is returned by selector, 
// Otherwise the element from Stream2 is appended to.
Stream<T> merge(Stream<? extends T> stream1, Stream<? extends T> stream2,
                BiFunction<? super T, ? super T, FirstSecond > selector);

Stream<T> merge(Iterator<? extends T> iterator1, Iterator<? extends T> iterator2, 
                BiFunction<? super T, ? super T, FirstSecond > selector);


public enum FirstSecond { // TODO rename it with an appropriate name
    FIRST, SECOND;
}
```

**Comment by PromanSEW** [comment]
Maybe `Selector` is the best variant for `FirstSecond` enum
Also, +1 for `concat` for iterators
@landawn please give example for using `merge` methods

**Comment by aNNiMON** [comment]
As of release 1.1.6, I  moved operators to the separate package `operators` for two reasons:

1. It's better than use anonymouse classes.
2. It allows to use any operator with `Iterator`s without creating `Stream` instance.

You need [`ObjConcat` ](https://github.com/aNNiMON/Lightweight-Stream-API/blob/a9ddfc197cd277b5a4e33c5e93feb5704d6449ef/stream/src/main/java/com/annimon/stream/operator/ObjConcat.java):

```java
Iterator it = new ObjConcat(it1, it2);
// Or
Stream stream = Stream.of(new ObjConcat(it1, it2));
```

About `merge` function. it's very specific as for me. I'll think about it later, thanks.

**Comment by landawn** [comment]
@PromanSEW 
Think about: there are two event sequences, ordered by time(e.g. read from log files from different servers), We want to merge the two sequences by event-time-order and process them one by one. We don't want and can't `Stream.concat(s1, s2).sorted(...)..`

@aNNiMON 
Sorry, I didn't get your points by the two reasons. what does it mean: "better than use anonymous classes" or "...without creating Stream instance"?

you think the code:
```java
Iterator<T> it = new ObjConcat(iter1, iter2);
// Or
Stream<T> s = Stream.of(new ObjConcat(iter1, iter2));
```
is Better than
```java
Stream s = Stream.concat(iter1, iter2)
```
Faster? simpler or easier to read?

**Comment by aNNiMON** [comment]
Oh, sorry for having poorly explained it. Prior to 1.1.6, anonymous classes were used:

```java
public <R> Stream<R> map(final Function<? super T, ? extends R> mapper) {
    return new Stream<R>(new LsaIterator<R>() {

        @Override
        public boolean hasNext() {
            return iterator.hasNext();
        }

       @Override
        public R nextIteration() {
            return mapper.apply(iterator.next());
        }
    });
}
```

There are some disadvantages:

1. It produces more bytecode with some other stuff like `Stream$N` classes and accessors for access private field in parent public class (`iterator` in `Stream`):

    ```java
    public Object nextIteration() {
        return mapper.apply(Stream.access$000(Stream.this).next());
    }
    ```

2. If you have iterator and want to apply `map` operator, you need to create `Stream` instance:

    ```java
    Iterator mapped = Stream.of(it1).map(func).iterator();
    ```

That's why I moved all anonymous classes to the separate package. And now you can operate with iterators without creating any Stream instance:

```java
Iterator mapped = new ObjMap(it1, func);
```

----

`Stream<T> s = Stream.concat(iter1, iter2)` is readable than `Stream<T> s = Stream.of(new ObjConcat(iter1, iter2));`, but I have some concerns: should there be methods that accept iterators as well as streams? Do they pollute the API?

**Comment by PromanSEW** [comment]
> @aNNiMON: should there be methods that accept iterators as well as streams? Do they pollute the API?
I think adding `concat` for iterators will be enough for now

**Comment by aNNiMON** [comment]
@PromanSEW ok.

@landawn, I propose to make `merge` operator even more flexible by adding third state `SKIP`:

```java
public enum MergeResult {
    FIRST, SECOND, SKIP;
}
```

**Comment by landawn** [comment]
> should there be methods that accept iterators as well as streams? Do they pollute the API?

I look over the methods defined in `Stream`, and agree with @PromanSEW , adding iterator for `concat` is enough so far.

> What's wrong with Stream.of(new ObjConcat(it1, it2));? Is it really so much more to write?

There is nothing wrong. it's just kind of verbose. Another more important reason, as mention from the begin, Since `zip` has two. and `zip/concat` belong to same _category operations_ to me. Either both don't have the method, or both have. It's important to keep them (API) consistent.

> ...operator even more flexible by adding third state SKIP

I'm not sure how to handle `SKIP`.

**Comment by landawn** [comment]
By the way, `MergeResult` not sounds good to me, because the enum is not defined for any `Result`, It's defined to tell which element should be selected in the specified input elements.

**Comment by aNNiMON** [comment]
Okay, I intentionally didn't merged #134  to be able to rename enum.

**Comment by PromanSEW** [comment]
Maybe `MergeAction` or similar?

**Comment by landawn** [comment]
Enn...`merge`: Which I meat is something like `merge insert`. for example:

```java
Stream<Integer> s1 = Stream.of(1, 3 5);
Stream<Integer> s2 = Stream.of(2, 4, 6);
Stream<Integer> s3 = Stream.merge(s1, s2, (a, b) -> return a <= b ? FIRST : SECOND); // 1, 2, 3, 4 ,5, 6
```
I took a quick look the [tests](https://github.com/aNNiMON/Lightweight-Stream-API/commit/9f5ed2e0c5d96646bb5d9e8037315aafdcb417d2)... it more likes `zip `to me. Probably I didn't clarify it clearly, or I misunderstood the code. Here is the general [difference between 'concat' and 'merge'](https://stackoverflow.com/questions/38903094/concat-vs-merge-operaror/38904515). I think we can wait if we didn't make it clearly yet. don't need to commit it next release right now.

@PromanSEW 
`Action` generally is a 'Function' and 'Consumer' in the functional programming. Here is just a `enum`. I was thinking to define `BiFunction<? super T, ? super T, Integer> selector`, but worry about people don't know '0' or '1' should be returned to choose the next element from the first Stream. If it's hard to name the `enum`. Maybe we just use `Integer' instead, and add the doc:

> The next element from the first Stream is chosen for the next element of the merged Stream if 0 is returned and the first Stream has more elements, otherwise the next element from the second stream is chosen for the next element of the merged Stream.

**Comment by PromanSEW** [comment]
@landawn I thought about using Integer
Here is my suggestion about it:
```java
public static final int FIRST = 1;
public static final int SECOND = 2;
public static final int SKIP = -1;
```

**Comment by aNNiMON** [comment]
```java
Stream s1 = [1, 3, 5]
Stream s2 = [2, 4, 6]
Stream merged = Stream.merge(s1, s2, (a, b) -> a <= b ? FIRST : SECOND);
// 1, 2, 3, 4 ,5, 6
```

I don't understand how to deal with iterators in this case? If we take FIRST, then we should move it1 to next, if SECOND, then it2 to next?

a | b | selector result
--|---|--
1 | 2 | FIRST
3 | 2 | SECOND
3 | 4 | FIRST
5 | 4 | SECOND
5 | 6 | FIRST
? | 6 | ????

What should we pass to `a` in the last iteration? What should we do when selector function always returns FIRST? How to check that streams over if stream1 is empty and stream2 has elements? We can't pass `null` if one of stream is empty.


Everything is extremely clear with the merge operator described in the link to StackOverflow. But it doesn't have selector function.

----

Here is the demo of my `merge` implementation:

![merge-16fps-w150](https://user-images.githubusercontent.com/1321838/27724008-6ab7204a-5d78-11e7-82c2-b57d9baf14d0.gif)

Okay, currently it can't achieve the result you described above. But I can add two more states FIRST_THEN_SECOND and SECOND_THEN_FIRST. And now we can take or skip the items we need. 

```java
Stream s1 = [1, 3, 5]
Stream s2 = [2, 4, 6]
Stream merged = Stream.merge(s1, s2, (a, b) -> a <= b ? FIRST_THEN_SECOND : SECOND_THEN_FIRST);
// 1, 2, 3, 4 ,5, 6
```

a | b | selector result
--|---|--
1 | 2 | FIRST_THEN_SECOND
3 | 4 | FIRST_THEN_SECOND
5 | 6 | FIRST_THEN_SECOND

Notice, this operator can't be used for sorting purposes. It just merges streams with an ability to skip elements.

**Comment by landawn** [comment]
Here is a basic implementation (not test yet)
```java
public class ObjMerge<T> extends LsaIterator<T> {
    static final Object NONE = new Object(); // TODO it's better to define it in some basic class and shared with other classes/methods.
    private final Iterator<? extends T> iter1;
    private final Iterator<? extends T> iter2;
    private final BiFunction<? super T, ? super T, Integer> selector;
    @SuppressWarnings("unchecked")
    private T first = (T) NONE;
    @SuppressWarnings("unchecked")
    private T second = (T) NONE;

    public ObjMerge(Iterator<? extends T> iter1, Iterator<? extends T> iter2, BiFunction<? super T, ? super T, Integer> selector) {
        this.iter1 = iter1;
        this.iter2 = iter2;
        this.selector = selector;
    }

    @Override
    public boolean hasNext() {
        return first != NONE || second != NONE || iter1.hasNext() || iter2.hasNext();
    }

    @SuppressWarnings("unchecked")
    @Override
    public T nextIteration() {
        if (hasNext() == false) {
            throw new NoSuchElementException();
        }

        if (first == NONE && iter1.hasNext()) {
            first = iter1.next();
        }
        if (second == NONE && iter2.hasNext()) {
            second = iter2.next();
        }

        T result = null;

        if (second == NONE || (first != NONE && selector.apply(first, second) == 1)) {
            result = first;
            first = (T) NONE;
        } else {
            result = second;
            second = (T) NONE;
        }

        return result;
    }
}
``` 

My suggestion is: let `merge` does `merge` and only does `merge`, `skip` can be done by `Stream.merge(...).skip(...)` or `Stream.merge(...).filter(...)`

**Comment by landawn** [comment]
> Notice, this operator can't be used for sorting purposes. It just merges streams with an ability to skip elements

It could be used for the sort purpose, but doesn't have to be it. the most important thing it gives people the control of the order of the elements occurring in the merged Stream, like event/log sample I mentioned above. `concat` is most likely appending elements after another stream.

**Comment by aNNiMON** [comment]
Please, explain to me, what should I pass to `a` in the last iteration?

a | b | selector result
--|---|--
1 | 2 | FIRST
3 | 2 | SECOND
3 | 4 | FIRST
5 | 4 | SECOND
5 | 6 | FIRST
? | 6 | ????

According to your code above, I should pass `Object NONE`, right? Don't you think it's a little wrong? I need to mark this constant as `public` and all people must write something like this in the selector function:

```java
Stream.merge(s1, s2, (a, b) -> {
    if (a == ObjMerge.NONE) return SECOND;
    if (b == ObjMerge.NONE) return FIRST;
    return a <= b ? FIRST : SECOND
});
```

**Comment by landawn** [comment]
Good catch! Since there is only one element for last, so no need to call the `selector` function. Here is the update:

```java
        ....
        T result = null;

        if (first == NONE) {
            result = second;
            second = (T) NONE;
        } else if (second == NONE) {
            result = first;
            first = (T) NONE;
        } else {
            if (selector.apply(first, second) == 1) {
                result = first;
                first = (T) NONE;
            } else {
                result = second;
                second = (T) NONE;
            }
        }

        return result;
```

**Comment by aNNiMON** [comment]
Now we have 3 varieties of the `merge` operator:

1. As suggested by @landawn 
2. Similiar to [Rx `merge` operator](https://stackoverflow.com/a/38904515/2135221)
3. My `merge` implementation with an ability to skip: element from stream A, from stream B, skip both elements or take both elements,

I prefer the second option, as it is most understandable and RxJava users can be familiar with it. Or the third option, as it is more flexible.

First option is unclear for me. @landawn says it can be used for sorting purposes, but:

```java
Stream s1 = [1, 4, 2, 0]
Stream s2 = [2, 6, 3, 1]
Stream merged = Stream.merge(s1, s2, (a, b) -> a <= b ? FIRST : SECOND);
// 1, 2, 4, 2, 0, 6, 3, 1
```

| a | b | selector result
|--|---|--
| 1 | 2 | FIRST
| 4 | 2 | SECOND
| 4 | 6 | FIRST
| 2 | 6 | FIRST
| 0 | 6 | FIRST
| `*` |

`*` now the stream A has finished and we take remaining elements of the stream B (am I right?)

To get the ordered stream we need to pass two **sorted** streams:

```java
Stream s1 = [1, 4, 2, 0]
Stream s2 = [2, 6, 3, 1]
Stream merged = Stream.merge(s1.sorted(), s2.sorted(), (a, b) -> a <= b ? FIRST : SECOND);
a: [0, 1, 2, 4]
b: [1, 2, 3, 6]
// 0, 1, 1, 2, 2, 3, 4, 6
```
 
This fact makes the use of the method very specific. I think, it would be better to call `sorted` after combining two streams.

**Comment by landawn** [comment]
@aNNiMON as I said before, it could be used for merging sort, but not necessary has to. for example, process the events from two event log files sorted by time. 
How do you implement the second approach?

**Comment by aNNiMON** [comment]
Finally, I understand you! It's merge sort for two sorted streams with some side effects such as concat:
```
Stream.merge(s1, s2, (a, b) -> FIRST); // -> Stream.concat(s1, s2);
Stream.merge(s1, s2, (a, b) -> SECOND); // -> Stream.concat(s2, s1);
```

Isn't it?

**Comment by aNNiMON** [comment]
See updated #134

**Comment by landawn** [comment]
```java
Stream.merge(s1, s2, (a, b) -> FIRST); // -> Stream.concat(s1, s2);
Stream.merge(s1, s2, (a, b) -> SECOND); // -> Stream.concat(s2, s1);
```
> Isn't it?

No. they're not equal.
If you already have the idea about how to implement the merge which is similar with the merge in RxJava, you will find that's exactly similar with my suggestion, you need to add the `function `parameter  to decide where the next element from.  the difference from RxJava is: RxJava is push.
