### ISSUE TITLE
Add Comparator for strings containing numbers

### ISSUE THREAD

**Issue by PromanSEW** [aNNiMON/Lightweight-Stream-API#138]
Default sorting of strings (`string1.compareTo(string2)`):
```
file1
file10
file2
```
This is wrong comparing method
What about adding `Comparator` that compares these strings right?

**Comment by aNNiMON** [comment]
You need Alphanumeric Comparator. I can't add it to my library since it very specific.  
Please, use this implementation https://github.com/sawano/alphanumeric-comparator.

**Comment by PromanSEW** [comment]
Thanks for library link. So, I think it may be closed
