### ISSUE TITLE
Stream.ofNullable(...) missing

### ISSUE THREAD

**Issue by petnagy** [aNNiMON/Lightweight-Stream-API#139]
There are 5 kind of Stream.of but there are 2 kind of Stream.ofNullable.

When I tried Stream.ofNullable(new Stream[20]).map(item -> ....) in this case item was String[] type instead of String.

    public static <T> Stream<T> ofNullable(final T... elements) {
        if (elements == null || elements.length == 0) {
            return Stream.<T>empty();
        }
        return new Stream<T>(new ObjArray<T>(elements));
    }

**Comment by aNNiMON** [comment]
Thanks for feedback. I'll add 3 missing methods.

P.S. Java 9 has only one [ofNullable method](http://download.java.net/java/jdk9/docs/api/java/util/stream/Stream.html#ofNullable-T-).

**Comment by petnagy** [comment]
Thanks!

**Comment by landawn** [comment]
Wait... are you sure you want to add ofNullable for other types?
```java
String str = null;
Stream.of(str) ... // Returns a stream with one null element.
Stream.ofNullable(str)... // Returns an empty Stream.
// There is the difference between `of` and `ofNullable` for single null element.

String[] strs = null;
Stream.of(strs)... // Throws NullPointerExeption.
Steam.ofNullable(strs) // Returns an empty Stream.
// what's the difference/relationship between `of` and `ofNullable` when the parameter is an array or collection? 
// One throwing exception, one doesn't? 
// To me, `ofNullable ` is replacement of `of`.  because there is no reason for the exist of `ofNullable` if `of` doesn't throw exception for null array/collection/...
// Basically, They're duplicated. I thank that's why there is no `ofNullable` for array/collection/... in JDK 9, NOT MISSING!

```

**Comment by petnagy** [comment]
The problem:
If you have an array like String[] someStrings = new String[10]; if you know it could not be null and you want to iterate over it you will use Stream.of(someString).map(item -> //item is a string

But if your array could be null you will use ofNullable in that case Stream.ofNullable(someString).map(item -> // hear item is an array instead of a string

So it would be great if ofNullable will give back the same type like of method.

**Comment by aNNiMON** [comment]
@landawn some people prefer error suppressing (Stream.of(null) that returns empty stream), others want to get an exception (Stream.of(null) that throws NullPointerException). So, it is important to have both methods.
