### ISSUE TITLE
Objects::nonNull

### ISSUE THREAD

**Issue by ened** [aNNiMON/Lightweight-Stream-API#151]
(Android user):

New Android Studio versions suggest me to replace the lambda construct: 
```
.filter(x -> x != null)
```

with a method reference to `Objects::nonNull`. However, this won't work for older Android versions as it's dependent on a certain SDK level (24).

Could the method therefore be added to this project?

```
    public static boolean nonNull(Object obj) {
        return obj != null;
    }
```

**Comment by PromanSEW** [comment]
Use the same method from `Objects` class from this library

**Comment by ened** [comment]
It's missing as of V1.1.9. I will find time to submit a PR unless it was omitted for a reason?

**Comment by PromanSEW** [comment]
Hmm... You're right. I think this class was fully backported

**Comment by aNNiMON** [comment]
Take a look at [`Predicate.Util.notNull()` method](http://static.javadoc.io/com.annimon/stream/1.1.9/com/annimon/stream/function/Predicate.Util.html#notNull--) it returns `Predicate` instance. There is no need to convert method reference to anonymous class in desugaring process for this approach.
However, you can submit a PR with additions to `Objects` class if these methods are still needed.

**Comment by ened** [comment]
`Predicate.Util.notNull` does not return a boolean, which is required for the `.filter` method above. The filter method is part of RxJava, hence the request. I will see about the PR. Thank you.

**Comment by aNNiMON** [comment]
You don't need to pass it as method reference. `filter` accepts `Predicate` object and `Predicate.Util.notNull` gives it.

**Comment by ened** [comment]
Great to see this change has been merged. @aNNiMON Maybe it is a good time to release a new version?

**Comment by aNNiMON** [comment]
@ened there are too few changes for the new release, but you can use current `master` snapshot via [jitpack](https://jitpack.io/#aNNiMON/Lightweight-Stream-API/master-SNAPSHOT).

**Comment by ened** [comment]
@aNNiMON A good idea, except that when using jitpack, gradle pulls in all of this projects test dependencies as regular dependencies. Not sure why that happens exactly. The gradle files here seem ok. I noticed it because pro guard complained about a TON of unknown classes in the final build (moskito etc).
