### ISSUE TITLE
Ambiguous method call

### ISSUE THREAD

**Issue by LuigiMaestrelli** [aNNiMON/Lightweight-Stream-API#156]
I just updated my Android to 3.1 and now the lint is highlighting all the comparing function as an error.
But, my app runs and compiles fine.

This is the message:

```
Ambiguous method call. Both comparing
(Function<? super ChatConversaDto, ? extends Date>) in ComparatorCompat and comparing
(Function<? super ChatConversaDto, ? extends Date>) in Comparator match
```
This is an example of my code:

```
List<MyDto> list = Stream.of( anotherList )
                            .sorted(comparing(AnotherListClass::getDate)
                                    .thenComparing(comparing(AnotherListClass::getIndex)))
                            .toList();
```

![error](https://user-images.githubusercontent.com/5038871/37992647-b1463e30-31e2-11e8-8580-eee1c89eca3a.png)

**Comment by aNNiMON** [comment]
@LuigiMaestrelli if you write code for Java 8 (Android API level 24+), then `default` methods appear in `java.util.Comparator` interface. This causes an error: compiler doesn't know which type is method reference - `java.​util.​function.Function` or `com.​annimon.​stream.​function.Function`. You can help the compiler by specifying the type of method reference. See this solution https://github.com/aNNiMON/Lightweight-Stream-API/issues/148#issuecomment-339897126

**Comment by LuigiMaestrelli** [comment]
Thank you.
