### ISSUE TITLE
Wrong inferred annotations appeared

### ISSUE THREAD

**Issue by PromanSEW** [aNNiMON/Lightweight-Stream-API#159]
I can't use method `Objects.requireNonNull` in Android Studio 3.1.1 (where IDEA 2017.3 was merged, with support of inferred annotations for parameters), because its argument is marked as `@NotNull` instead of `@Nullable`.
Also, this method and parameterized versions must be annotated by `@Contract("null -> fail")` and `@Contract("null, _ -> fail")` respectively.

Please add provided dependency `org.jetbrains:annotations-java5:15.0` and add these annotations for methods above.
For example:
```java
@Contract("null, _ -> fail")
public static <T> T requireNonNull(@Nullable T obj, String message) {
...
}
```

See https://www.jetbrains.com/help/idea/annotating-source-code.html for more information.

P.S. IntelliJ IDEA allows to configure external annotations path, and set these annotations manually, but Android Studio has other mechanism for this feature, and it is awkward (see https://stackoverflow.com/a/46546409/4858673 ).
Folder `.idea/libraries` is not under VCS, and these settings may be cleared after library update.

So, I'd like to use these methods, but Android Studio marks invocation as NPE problem.

Other methods which I am using have right inferred annotations.

**Comment by PromanSEW** [comment]
Other solution is creating issue in Android Studio bug tracker

**Comment by aNNiMON** [comment]
Can you try [this](https://github.com/aNNiMON/Lightweight-Stream-API/tree/iss159) branch via JitPack?
```
implementation 'com.github.aNNiMON:Lightweight-Stream-API:iss159-SNAPSHOT'
```

**Comment by PromanSEW** [comment]
@aNNiMON I copied changed method to my code and check manually. Works fine! 👍

**Comment by aNNiMON** [comment]
Thanks for testing :+1: 

Anyway, there's no difference between

```java
if (condition) throw Exception();
return obj;
```
and 
```java
if (condition) throw Exception();
else return obj;
```
in bytecode. Both variants produces same instructions:

```java
public static <T> T requireNonNull(T);
  Code:
     0: aload_0
     1: ifnonnull     12
     4: new           #2   // class java/lang/NullPointerException
     7: dup
     8: invokespecial #3   // Method java/lang/NullPointerException."<init>":()V
    11: athrow
    12: aload_0
    13: areturn
```

if IJ/AS parses source code, it should be easier to identify the annotations correctly.
I think, this problem deserves an issue in bug tracker.
