### ISSUE TITLE
Collectors.map not implemented

### ISSUE THREAD

**Issue by Dima564** [aNNiMON/Lightweight-Stream-API#16]

**Comment by javadev** [comment]
I have not found this method in java 8 documentation:

https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html

**Comment by Dima564** [comment]
http://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html#toMap-java.util.function.Function-java.util.function.Function-

**Comment by aNNiMON** [comment]
@Dima564 this method [already implemented](https://github.com/aNNiMON/Lightweight-Stream-API/blob/master/src/main/java/com/annimon/stream/Collectors.java#L84-L88), but there is old version in Maven. I will update it soon.

**Comment by Dima564** [comment]
@aNNiMON Thanks!
