### ISSUE TITLE
Cant able to combine multiple Predicate.

### ISSUE THREAD

**Issue by SunnyJithin** [aNNiMON/Lightweight-Stream-API#164]
I am using this to combine multiple predicates. Is there any cleaner method to replace this.

Stream.of(originalSearchList)
                .filter(predicate1).filter(predicate2).filter(predicate3).collect(Collectors.toList());

**Comment by PromanSEW** [comment]
For two predicates you can use `Predicate.Util.and(predicate1, predicate2)`.
Unfortunately there is no method for combining 3+ predicates, but you can implement this feature.
```java
public static <T> Predicate<T> and(Predicate<T> predicates...) {
  return new Predicate<T>() {
    public boolean test(T t) {
     for (Predicate<T> p : predicates) {
       if (!p.test(t)) return false;
     }
     return true;
   }
  }
}
```

**Comment by aNNiMON** [comment]
@PromanSEW it would be nice. I'll add this soon.

**Comment by PromanSEW** [comment]
@aNNiMON do not forget also `or` and `not` methods :)

**Comment by aNNiMON** [comment]
@PromanSEW what should return `not` for multiple predicates?
