### ISSUE TITLE
Samples using Stream on Android SDK 21+

### ISSUE THREAD

**Issue by ArcherEmiya05** [aNNiMON/Lightweight-Stream-API#166]
Hello this is not an issue at all but I'm not familiar with Java 8 Stream and I cant use that API in my Android
app because of SDK incompatibility. Anyway could you help me or give me the correct algorithm for checking if a List containing an Object with some properties like id is equal to a value of string x that returns a boolean value. This is to check first if the incoming object with id is already an existing object before adding it to List. I do not want to iterate to the list just to check for it unless I will use the index right? Sorry for the inconvenience and Thanks in advance.

Example 

This method will return true if the List<MyObject> contains a MyObject with the name **name**. If you want to perform an operation on each of the MyObjects that getName().equals(name), then you could try something like this:

        public void perform(final List<MyObject> list, final String name){
        return list.stream().filter(o -> o.getName().equals(name)).forEach(
            o -> {
                //...
            }
         );
         }
Where o represents a MyObject instance.

**Comment by javadev** [comment]
Issue may be closed.
