### ISSUE TITLE
Add sonarcloud integration

### ISSUE THREAD

**Issue by javadev** [aNNiMON/Lightweight-Stream-API#171]
What we need is a string in .travis.yml for maven project:

after_success:
  - mvn sonar:sonar -Dsonar.projectKey=javadev_underscore-java -Dsonar.organization=javadev-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=ae***d

And create a new project, site url:
https://sonarcloud.io

**Comment by javadev** [comment]
!

**Comment by aNNiMON** [comment]
I tried to connect it with the gradle project, but due to lack of documentation it was unsuccessfull.

**Comment by aNNiMON** [comment]
Thanks. Looks like it works now.

**Comment by aNNiMON** [comment]
It seems a plugin doesn't work with Cobertura, only JaCoCo.

**Comment by javadev** [comment]
It is time to migrate from Cobertura to JaCoCo. 👍
