### ISSUE TITLE
Why does Optional.of(List<String).stream() return a stream with a single element, the List<String> instead of a Stream of individual elements?

### ISSUE THREAD

**Issue by johnnylambada** [aNNiMON/Lightweight-Stream-API#173]
I have an API that returns `Response<List<Thing>>`, and I'd like to validate the Response, then get the List<Thing> and turn that into a Stream.of(Thing), but I have to do an awkward `.map(Stream::of).orElse(Stream.empty())` instead of the more intuitive `.stream()` because `.stream()` just gives me a stream of the `List<Thing>` instead of multiple `Things`. Is this by design?

```
        final List<String> flintstones = new ArrayList<String>(){{
            add("Fred");
            add("Wilma");
            add("Pebbles");
            add("Dino");
        }};
        Optional.ofNullable(flintstones)
//                .stream()                                 // gives me a stream with a single value: List<String>
                .map(Stream::of).orElse(Stream.empty())     // gives me what I want, four Strings
                .forEach(System.out::println);
```

**Comment by aNNiMON** [comment]
Yes, this method by contract converts `Optional<T>` to `Stream<T>`, so `Optional<List<String>>`  is converted to `Stream<List<String>>` and `Optional<String>` to `Stream<String>`. It's simple and flexible solution.

If you have `Optional<List<String>>` and want `Stream<String>`  just use `flatMap` operator:

```java
Optional.ofNullable(flintstones)
        .stream()
        .flatMap(Stream::of)
        .forEach(System.out::println);
```

or use `Stream.ofNullable`

```java
Stream.ofNullable(flinstones)
        .forEach(System.out::println);
```

**Comment by johnnylambada** [comment]
Ah! .flatMap -- thanks!

**Comment by edbka** [comment]
not work in java21, use flatMap(Collection::stream)

```java
Optional.ofNullable(flintstones)
        .stream()
        .flatMap(Collection::stream)
        .forEach(System.out::println);
```
