### ISSUE TITLE
Not maintaining the order while groupBy

### ISSUE THREAD

**Issue by Bugzer0** [aNNiMON/Lightweight-Stream-API#175]
In java 8, use LinkedHashMap::new to keep the order.
example: 
`final LinkedHashMap<Integer, List<String> map = myList
            .stream()
            .sorted(Comparator.comparing(p -> p.getAge())) //sort list by ages
            .collect(Collectors.groupingBy(p -> p.getAge()),
                    LinkedHashMap::new, //keep the order
                    Collectors.mapping(p -> p.getName(), //map name
                            Collectors.toList())));`
In Lightweight-Stream-API, how to use it?

**Comment by aNNiMON** [comment]
Same as in Java 8. There is [Collector s.groupingBy](http://static.javadoc.io/com.annimon/stream/1.2.1/com/annimon/stream/Collectors.html#groupingBy-com.annimon.stream.function.Function-com.annimon.stream.function.Supplier-com.annimon.stream.Collector-) method which takes Supplier for producing containers as second argument.

The only difference in creating a Stream: `Stream.of(myList)`

**Comment by Bugzer0** [comment]
My code in Java 8:
`myList.stream().collect(Collectors.groupingBy(p -> p.getAge(), LinkedHashMap::new, Collectors.toSet()));`
How to convert to Lightweight-Stream-API?

**Comment by Bugzer0** [comment]
Thank for your reply, my problem has been solved
