### ISSUE TITLE
Add nullability annotations for better Kotlin support

### ISSUE THREAD

**Issue by bejibx** [aNNiMON/Lightweight-Stream-API#176]
Consider following code kotlin:
```kotlin
val s: String? = null
val e = Exceptional.of { s }
val o: Optional<String> = e.optional
```
This will not compile because inferred type of ```e.optional``` is ```Optional<String?>``` which is meaningless because of ```Optional``` class nature.

To fix this we are forced to do some dirty hacks like this: ```e.optional.map { it!! }``` which is very confusing.

I can add nullability annotations support by myself, but I'm wondering maybe there was a reason why wasn't this done already? Also which nullability annotations should we use? [JSR305](https://jcp.org/en/jsr/detail?id=305)? @aNNiMON what's your opinion on this?

**Comment by DAPolyakov** [comment]
Yes! This is a very necessary feature! Nice man, @bejibx!

**Comment by aNNiMON** [comment]
@bejibx thanks for nice suggestion! 
I think it's better to use `org.jetbrains.annotations-java5` (Note, this project targets Java 1.6). It has `@Contract` annotation, that may be useful too, see #159
