### ISSUE TITLE
Add teeing collector

### ISSUE THREAD

**Issue by aNNiMON** [aNNiMON/Lightweight-Stream-API#178]
JDK 12 [teeing​(Collector, Collector, BiFunction)](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/stream/Collectors.html#teeing(java.util.stream.Collector,java.util.stream.Collector,java.util.function.BiFunction))

**Comment by thniig** [comment]
@aNNiMON 

_Sent from my moto e(5) cruise using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
