### ISSUE TITLE
0.0% Coverage on New Code is less than 80.0%

### ISSUE THREAD

**Issue by javadev** [aNNiMON/Lightweight-Stream-API#180]

**Comment by aNNiMON** [comment]
Coverage is [99.973% now](https://coveralls.io/github/aNNiMON/Lightweight-Stream-API?branch=master). Thanks for pointing out the error. 

Sonarcloud coverage is still broken.

**Comment by javadev** [comment]
It looks like cobertura is not compatible with sonar. It nay be replaced with jacoco.

**Comment by javadev** [comment]
🙄

**Comment by aNNiMON** [comment]
Fixed

**Comment by sarita26687** [comment]
how did you fixed this. please help me resolving the above mentioned issue

**Comment by aNNiMON** [comment]
@sarita26687 switching to jacoco helped me. See https://github.com/aNNiMON/Lightweight-Stream-API/commit/9c3b7f19298c19a2ea04ef573091aa0dc7fb5760
