### ISSUE TITLE
How to get map return

### ISSUE THREAD

**Issue by rohmanureldi** [aNNiMON/Lightweight-Stream-API#182]
Hey, i am just discover your api. I wonder how you convert this code below to yours. Sorry for my question. Good API tho!

Map<String, Float> sorted = hasil
                .entrySet()
                .stream()
                .sorted(Collections.reverseOrder(Map.Entry.comparingByValue()))
                .collect(toMap(Map.Entry::getKey, Map.Entry::getValue, (e1, e2) -> e2,
                        LinkedHashMap::new));

**Comment by aNNiMON** [comment]
@rohmanureldi library uses a similar to standard API: Try this:

```
Map<String, Float> sorted = Stream.of(hasil.entrySet())
    .sorted(Collections.reverseOrder((c1, c2) -> c1.getValue().compareTo(c2.getValue())))
    .collect(Collectors.toMap(
            Map.Entry::getKey,
            Map.Entry::getValue,
            (e1, e2) -> e2,
            LinkedHashMap::new));
```

Note `Map.Entry.comparingByValue()` isn't provided in library.

**Comment by javadev** [comment]
Issue may be closed
