### ISSUE TITLE
BUG: function not work as java9 standard

### ISSUE THREAD

**Issue by wjtxyz** [aNNiMON/Lightweight-Stream-API#186]
same expression different result

```
        String s1 = "" + java9.util.stream.Stream.iterate(new AtomicInteger(0), s -> s.incrementAndGet() < 3, s -> s).findFirst(); 
        //s1=Optional[1]

        String s2 = "" + com.annimon.stream.Stream.iterate(new AtomicInteger(0), s -> s.incrementAndGet() < 3, s -> s).findFirst();
        //s2=Optional[2]

```

java9 function
`public static <T, S extends T> Stream<T> iterate(S seed, Predicate<? super S> hasNext, UnaryOperator<S> next){}`

**Comment by aNNiMON** [comment]
@wjtxyz yeah, the problem was in `takeWhile` iterator. It calls `hasNext` twice. Nice catch, fixed! :+1:
