### ISSUE TITLE
Make java 11 as a minimum version

### ISSUE THREAD

**Issue by javadev** [aNNiMON/Lightweight-Stream-API#189]
Java 11 was released in September 2018 - 4 years ago.

It's time to make it as a minimum java version.

**Comment by aNNiMON** [comment]
I think it's not necessary. Code compiles fine with Java 6+, it doesn't need any Java 8 dependencies, so why?
Btw, Kotlin compiler [can still target 1.6](https://kotlinlang.org/docs/reference/faq.html#which-versions-of-jvm-does-kotlin-target)

**Comment by javadev** [comment]
We can setup target for kotlin.

**Comment by javadev** [comment]
For kotlin 1.5 java 8 is default target.

**Comment by aNNiMON** [comment]
@javadev switching to Java 8 may cause some problems on Android API < 24. A small analysis is needed.

**Comment by javadev** [comment]
I prepared code changes https://github.com/aNNiMON/Lightweight-Stream-API/pull/196

**Comment by dujianchi** [comment]
I use this library on Android, which gives me Stream compatibility on devices below API 24. I think this is fine, if the target version is set to 8, why not just use the STREAM API of JDK8?
