### ISSUE TITLE
Where you wrote "compile" you meant "classpath" in your Readme (gradle setup)

### ISSUE THREAD

**Issue by entangledloops** [aNNiMON/Lightweight-Stream-API#21]

**Comment by aNNiMON** [comment]
What's wrong? According to [Gradle, please](http://gradleplease.appspot.com/#stream) service:
```
dependencies {
    compile 'com.annimon:stream:1.0.5'
}
```

[build.gradle](https://github.com/aNNiMON/Android-Java-8-Stream-Example/blob/master/app/build.gradle#L43)
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.annimon:stream:1.0.3'
    compile 'com.android.support:appcompat-v7:23.0.1'
}
```

`classpath` mostly used for gradle plugins or dependencies:
```
buildscript {
    dependencies {
        classpath 'me.tatarka:gradle-retrolambda:3.2.2'
    }
}
```

**Comment by entangledloops** [comment]
Ah, I see. Not familiar enough with gradle. Maybe add the buildscript example to the readme, as I would have found it instructive. (The library is working great, thanks for providing it!)
