### ISSUE TITLE
Concat applied after filter produces unexpected result

### ISSUE THREAD

**Issue by kotucz** [aNNiMON/Lightweight-Stream-API#23]
Applying `concat()` on stream that is result of `filter()` produces incorrect result.
Below is new test that reproduces the issue:

    @Test
    public void testConcatOfFilter() {
        final PrintConsumer consumer = new PrintConsumer();
        final Stream<Integer> first = Stream.ofRange(0, 5)
            .filter(it -> true);
        final Stream<Integer> second = Stream.ofRange(5, 10)
            .filter(it -> true);
        Stream.concat(first, second)
            .forEach(consumer);
        assertEquals("0123456789", consumer.toString());
    }

    org.junit.ComparisonFailure: 
    Expected :0123456789
    Actual   :13null56789

The issue is that `hasNext()` implementation in `filter()` is not idempotent - when called multiple times, value is skipped.
In `concat()` implementation the (`filter()` `hasNext()`) is called once in `hasNext()` and once in `next()`, which would be ok, if `filter()` `hasNext()` did not have the side-effect.

**Comment by aNNiMON** [comment]
Fixed! Thank you so much, @kotucz

**Comment by kotucz** [comment]
Thanks for the quick fix!

Just one note - this implementation assumes that `hasNext()` is called at least once before `next()`.
So just calling `next()` could break something (but this probably will never happens inside the library).
For inspiration the same thing is in guava  `Iterators.filter()` (which is not a lightweight dependency though).

**Comment by aNNiMON** [comment]
Fixed with 80885bbdc17e67dd4494d9e03c02e3f31fe88d41
