### ISSUE TITLE
"ofRange()" would be better to be "range()"

### ISSUE THREAD

**Issue by ypresto** [aNNiMON/Lightweight-Stream-API#27]
First, thanks for great library!

I want to change method name of "ofRange()" to "range()" because following reasons:

- Java 8 Stream API has `range()` class method on IntStream and LongStream, not `ofRange()`.
- I wrote "of()" instead of "ofRange()" by mistake, then it compiled successfully and caused bug...

**Comment by aNNiMON** [comment]
Thank you, @ypresto. `ofRange` and `ofRangeClosed` is now deprecated.

**Comment by ypresto** [comment]
thanks!!! :tada:
