### ISSUE TITLE
Consider adding support for unit testing (enhancement)

### ISSUE THREAD

**Issue by xsveda** [aNNiMON/Lightweight-Stream-API#36]
In all projects where I use Stream API I have Hamcrest [OptionalMatcher.java](https://gist.github.com/xsveda/37d3fb8b87f618833923)

It would be nice to have such Hamcrest support (and not only for Hamcrest) for testing directly in the library.
Tricky part is where to put such support as having it in core library artifact might be confusing. On the other hand this approach is used by some other libraries, i.e. RxJava and its [TestObserver](https://github.com/ReactiveX/RxJava/blob/f2410f88dc28c1013f48754606e38507e493245f/src/main/java/rx/observers/TestObserver.java)
Other option is to create additional artifact only for testing.

What do you think?

**Comment by aNNiMON** [comment]
I'm not familiar Hamcrest so good, what should support a library in addition to `Optional` test methods? I wouldn't want to add dependencies to the library, but somethink like `TestObserver` class could be added.

**Comment by xsveda** [comment]
Well the matcher is not testing behavior of `Optional` but rather a state of some Optional value in target application's tests. 
Instead of 
`assertTrue(database.getUser(id).isPresent())`
`assertFalse(database.getUser(id).isPresent())`
you can write
`assertThat(database.getUser(id), isPresent())`
`assertThat(database.getUser(id), isEmpty())`
With Hamcrest you may use only `assertThat()` structure with matchers that ends up with more clean and fluent test asserts.
And it might not be only about `Optional`.

Regarding the new dependency of course it would be wrong to add Hamcrest as transitive dependency but there are other options:

1. Add Hamcrest as runtime dependency. Only Applications that will use these testing support classes will have to add Hamcrest to classpath.
2. Create separate artifact with testing support only that can be that used as testing dependency only (i.e. `testCompile 'com.annimon:stream-test:1.0.8'`)

**Comment by aNNiMON** [comment]
Thanks for explanation. Separate artifact `stream-test` would be great. I'll think about it.

**Comment by aNNiMON** [comment]
@xsveda I just released [`stream-test:1.0.0` artifact](http://search.maven.org/#artifactdetails%7Ccom.annimon%7Cstream-test%7C1.0.0%7Cjar). It contains Optional `isEmpty`, `isPresent` and Stream `isEmpty`, `isNotEmpty`, `elements`  matchers. 
Feel free to suggest any other matchers.

**Comment by xsveda** [comment]
@aNNiMON Thank you for that! Sorry for not replying I'm quite busy right now. I have some more ideas in my head and will get to is soon I hope. Feel free to close this one for now or we can leave it open for further discussion.
