### ISSUE TITLE
RemoveIf method

### ISSUE THREAD

**Issue by fabgio** [aNNiMON/Lightweight-Stream-API#43]
Hi
It would be nice if the removeIf method will be implemented.
Good job

**Comment by aNNiMON** [comment]
Hi, @fabgio. What should this method do? Is it inversed `filter` operation?

**Comment by fabgio** [comment]
Yes,according to java8 API It removes an element matching a given predicate.
All the best!
Il 07 apr 2016 12:41 PM, "Victor Melnik" <notifications@github.com> ha
scritto:

**Comment by aNNiMON** [comment]
I'll implement this method as `filterNot`, like in Scala and Kotlin. Actually, Stream doesn't remove anything, only filters.

**Comment by fabgio** [comment]
Actually in Java8 the removeIf method is implemented by the Collection 
interface

http://docs.oracle.com/javase/8/docs/api/java/util/Collection.html#stream--


Il 07/04/2016 16:58, Victor Melnik ha scritto:

**Comment by aNNiMON** [comment]
@fabgio oh, sorry for my misunderstanding. JDK8 method `removeIf` works with collections, not with stream. You can implement it themselves.
