### ISSUE TITLE
Lacking JavaDocs

### ISSUE THREAD

**Issue by awendland** [aNNiMON/Lightweight-Stream-API#5]
It would be wonderful if this library had javadocs for each of its methods. It would probably be possible to just copy the Java 8 Stream docs over where applicable.

**Comment by awendland** [comment]
I can probably open a pull request with this feature later this week

**Comment by aNNiMON** [comment]
@awendland thank you. It would be great.

**Comment by aNNiMON** [comment]
Closed by 1bd4db24ba507a3bc4ac9f01c8bf34578860d5af

**Comment by jeffhtli** [comment]
👍
