### ISSUE TITLE
filter().findFirst() behaves incorrectly in certain circumstances

### ISSUE THREAD

**Issue by optisamit** [aNNiMON/Lightweight-Stream-API#53]
This code
`Stream.iterate(0, i -> i+1).filter(i -> i == 0).findFirst()`
Will loop forever instead of returning the first element

**Comment by aNNiMON** [comment]
@optisamit thanks for pointing that out.

**Comment by optisamit** [comment]
@aNNiMON Thank you! In what version will the fix be included?

**Comment by aNNiMON** [comment]
@optisamit I'll publish 1.1.2 version this week.
