### ISSUE TITLE
Needs build management

### ISSUE THREAD

**Issue by awendland** [aNNiMON/Lightweight-Stream-API#6]
It would be easier to add to this project if it had something like Gradle or Maven for handling building and testing. I may be confused because I don't understand what the nbproject folder is (though it appears to be an IDE/machine specific folder that should not be under version control).

**Comment by aNNiMON** [comment]
@awendland this is NetBeans project and it uses [ant](http://ant.apache.org/) to build or test. See [this page](https://ant.apache.org/manual/running.html) for more information about runnig ant from command line.

**Comment by awendland** [comment]
Where are dependencies declared by the ant tool? The tests are dependent on JUnit but `ant` is failing to compile the tests because it's missing the JUnit package.

**Comment by aNNiMON** [comment]
@awendland in `project.properties` add line
`libs.junit_4.classpath=path/to/JUnit.jar`
or add test dependencies to [this property](https://github.com/aNNiMON/Lightweight-Stream-API/blob/master/nbproject/project.properties#L44-L47).

**Comment by awendland** [comment]
Would you be open a separate pull request that modifies this project to be
based on Gradle?

**Comment by aNNiMON** [comment]
Okay, I'll add Gradle project soon.

**Comment by awendland** [comment]
I've submitted a pull request to add Maven as the build system at https://github.com/aNNiMON/Lightweight-Stream-API/pull/7

**Comment by awendland** [comment]
Closed by 393cfe17f07e24b3b64c3c51e9aa4d1264fd09f0
