### ISSUE TITLE
Conflict in Gradle dependencies when using version 1.1.0 with test support 1.0.1

### ISSUE THREAD

**Issue by xsveda** [aNNiMON/Lightweight-Stream-API#60]
With `build.gradle` configuration
```
...
    compile "com.annimon:stream:1.1.0"
    testCompile "com.annimon:stream-test:1.0.1"
...
```
the build will fail with:
`Error:Conflict with dependency 'com.annimon:stream'. Resolved versions for app (1.1.0) and test app (1.0.9) differ. See http://g.co/androidstudio/app-test-app-conflict for details.`

Also please consider to always use the same version for `stream-test` module and the corresponding `stream` module to avoid any confusion.

**Comment by aNNiMON** [comment]
@xsveda that's my mistake, I will fix that on next release. Thanks.

The problem is that it is necessary to update `stream-test` on each `stream` release, even if there were no changes. Is it normal practice?
