### ISSUE TITLE
Add CI server integration

### ISSUE THREAD

**Issue by bryant1410** [aNNiMON/Lightweight-Stream-API#75]
In my opinion it would be cool if you add a CI server integration to this repo. So tests can be run automatically with PRs.

**Comment by aNNiMON** [comment]
There is Travis CI in this repo and it works fine. https://travis-ci.org/aNNiMON/Lightweight-Stream-API

**Comment by bryant1410** [comment]
Oh, my bad. After I sent the two recent PRs, I saw that there were no pending status shown, so I thought it wasn't set up.
