### ISSUE TITLE
Collectors Map

### ISSUE THREAD

**Issue by Dwite** [aNNiMON/Lightweight-Stream-API#8]
Any chances for [groupingBy] (https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html#groupingBy-java.util.function.Function-) function ?)

**Comment by aNNiMON** [comment]
@Dwite why not? Can you give few examples for this function with results?

**Comment by Dwite** [comment]
@aNNiMON most interesting you can read [here] (http://www.leveluplunch.com/java/examples/java-util-stream-groupingBy-example/) .

My own - 

```java
 Integer partitionItem = 1;
        List<Integer> items = Arrays.asList(1, 2, 3, 1, 2, 3, 1, 2, 3);

        Map<Boolean, List<Integer>> groupedBy = items.stream()
                .collect(Collectors.groupingBy(i -> i.equals(partitionItem)));

        items = new ArrayList<>(groupedBy.get(true));
        items.addAll(groupedBy.get(false));
        System.out.println(ones);
```

You group items by function into Map
