### ISSUE TITLE
If this is Java 7 you can use the diamon operator in some places

### ISSUE THREAD

**Issue by nicenemo** [aNNiMON/Lightweight-Stream-API#81]
I embedded your code into my Eclipse project because I want to make some changes you might not like. Eclipse mentioned that in some places the Diamond operator could be used. Not sure what JVM you are targeting.

**Comment by aNNiMON** [comment]
Library targets Java 6 for compatibility with old Android build tools. There is no need to upgrade project to Java 7.

**Comment by javadev** [comment]
Issue may be closed, I think.
