### ISSUE TITLE
IntGenerator is not Autocloseable

### ISSUE THREAD

**Issue by nicenemo** [aNNiMON/Lightweight-Stream-API#82]
Not sure whether it makes sense but found when backporting some code. Your IntGenerator is not autocloseable.

**Comment by aNNiMON** [comment]
Unfortunately I can't implement `AutoCloseable` interface in Java 6 project. It was introduced in Java 7.

**Comment by javadev** [comment]
Issue may be closed, I think.

**Comment by aNNiMON** [comment]
Okay, issue might be reopened if the library will be migrated to Java 7.

**Comment by aNNiMON** [comment]
Oops, `Closeable` already `extends AutoCloseable` in Java 7+.
