### ISSUE TITLE
Where is DoubleStream?

### ISSUE THREAD

**Issue by PromanSEW** [aNNiMON/Lightweight-Stream-API#83]
Why you added IntStream, but not DoubleStream?
Because it is a _lightweight_ library without all features of original Stream API?

**Comment by nicenemo** [comment]
It is easy to add it yourself and make the addition and do a pull request. Please ad LongStream and if You can BoolStream, CharStream and ShortShortStream.
 I forked the lib for other reasons after I was halfway my own implementation.

**Comment by aNNiMON** [comment]
@PromanSEW currently `LongStream` and `DoubleStream` are not implemented. Use `Stream<Long>` and `Stream<Double>` instead.

**Comment by nicenemo** [comment]
that means boxing.

**Comment by PromanSEW** [comment]
@nicenemo you are right, so I create this issue. Array of array of double (double[][]) is not supported by flatMap, after second applying it is still double[], and doesn't flatten to Stream of double. Stream<Double> is not applicable for non-boxed array

**Comment by aNNiMON** [comment]
@PromanSEW, you can use this simple workaround until I implement DoubleStream:

```java
double[][] input = {{1.0, 2.0}, {3.0, 4.0}, {5.0, 6.0}};
Stream.of(input)
        .flatMap(arr -> IntStream.range(0, arr.length).mapToObj(i -> arr[i]))
        .forEach(System.out::println);
````

**Comment by PromanSEW** [comment]
@aNNiMON thanks for this solution. Still watching for development of this useful library
