### ISSUE TITLE
DoubleStream, LongStream, IntStream are incompatible with Stream

### ISSUE THREAD

**Issue by PromanSEW** [aNNiMON/Lightweight-Stream-API#87]
Why? I want to flatten `double[][]`, but I can't
`Stream.of(dm).flatMap(DoubleStream::of)` says about incompatible types, because DoubleStream extends Object, not Stream
And `Stream.of`can't process primitive types - result is still `double[]`
I think this problem was fixed in 1.1.4
How to flatten multidimensional arrays of primitives?
Maybe I missed something?

**Comment by aNNiMON** [comment]
Class `Stream` represents object stream, use `IntStream`, `LongStream`, `DoubleStream` for primitives.

To flatten `double[][]` use `flatMapToDouble`:

```java
DoubleStream doubles = Stream.of(dm).flatMapToDouble(DoubleStream::of);
```

**Comment by PromanSEW** [comment]
Thanks, I don't know about these new methods

**Comment by aNNiMON** [comment]
That's all right. There are special methods to convert between Streams: 

| from \\ to   | Stream        | IntStream               | LongStream                | DoubleStream                  |
|--------------|---------------|-------------------------|---------------------------|-------------------------------|
| Stream       | map / flatMap | mapToInt / flatMapToInt | mapToLong / flatMapToLong | mapToDouble / flatMapToDouble |
| IntStream    | mapToObj      | map / flatMap           | mapToLong                 | mapToDouble                   |
| LongStream   | mapToObj      | mapToInt                | map / flatMap             | mapToDouble                   |
| DoubleStream | mapToObj      | mapToInt                | mapToLong                 | map / flatMap                 |
