### ISSUE TITLE
Nested Stream produces Error

### ISSUE THREAD

**Issue by mishkaowner** [aNNiMON/Lightweight-Stream-API#88]
Nested Stream.of and Stream.zip creates Error

While below produces error such as the data type of value2 in stream2 is WRONG:
`Stream<ChatAnswer> stream2 = Stream.zip(Stream.range(0, 4).flatMap(i -> Stream.of(new ChatAnswer())), Stream.of(ansTypes), (value1, value2) -> { value1.setAnswerType(value2); return value1; });

Stream.zip(stream1, stream2, (value1, value2) -> {value1.getAnswers().add(value2); return value1;}).forEach(chatQuestion -> chatQuestions.add(chatQuestion));`

Solution: 

`Stream<ChatAnswer> str1 = Stream.range(0, 4).flatMap(i -> Stream.of(new ChatAnswer()));
Stream<Integer> dd = Stream.of(ansTypes);
Stream<ChatAnswer> stream2 = Stream.zip(str1, dd, (value1, value2) -> { value1.setAnswerType(value2); return value1; });

Stream.zip(stream1, stream2, (value1, value2) -> {value1.getAnswers().add(value2); return value1;}).forEach(chatQuestion -> chatQuestions.add(chatQuestion));`

By separating into smaller streams helps as it indicates what the stream returns as its generic type.
For now, Im going to use Rx as the replacement.

**Comment by mishkaowner** [comment]
I reckon, I need to check if this problem Is related with Retrolambda instead.

**Comment by aNNiMON** [comment]
@mishkaowner thanks for feedback. 

<details>
<summary>I've tried to reproduce the issue with this code</summary>

```java
import com.annimon.stream.Stream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public final class Issue88 {
    
    public static void main(String[] args) {
        final List<AnswerType> ansTypes = Arrays.asList(AnswerType.values());

        Stream<ChatQuestion> stream1 = Stream.range(0, 4)
                        .flatMap(i -> Stream.of(new ChatQuestion()));
        Stream<ChatAnswer> stream2 = Stream.zip(
                Stream.range(0, 4)
                        .flatMap(i -> Stream.of(new ChatAnswer())),
                Stream.of(ansTypes),
                (value1, value2) -> {
                    value1.setAnswerType(value2);
                    return value1;
                });

        final List<ChatQuestion> chatQuestions = new ArrayList<>();
        Stream.zip(stream1, stream2, (value1, value2) -> {
            value1.getAnswers().add(value2);
            return value1;
        }).forEach(chatQuestion -> chatQuestions.add(chatQuestion));

        Stream.of(chatQuestions).forEach(System.out::println);
    }

    private static class ChatQuestion {

        private final List<ChatAnswer> answers;

        public ChatQuestion() {
            this.answers = new ArrayList<>();
        }

        public List<ChatAnswer> getAnswers() {
            return answers;
        }

        @Override
        public String toString() {
            return "ChatQuestion: " + answers.toString();
        }
    }

    private static class ChatAnswer {

        private AnswerType answerType;

        public void setAnswerType(AnswerType type) {
            this.answerType = type;
        }

        @Override
        public String toString() {
            return "ChatAnswer{" + "answerType=" + answerType + '}';
        }
    }

    private enum AnswerType { TYPE1, TYPE2, TYPE3, TYPE4 };
}
```

</details>  

but it works fine and returns:

```
ChatQuestion: [ChatAnswer{answerType=TYPE1}]
ChatQuestion: [ChatAnswer{answerType=TYPE2}]
ChatQuestion: [ChatAnswer{answerType=TYPE3}]
ChatQuestion: [ChatAnswer{answerType=TYPE4}]
```

Tried on 1.1.2 and 1.1.4 versions.

**Comment by javadev** [comment]
Issue.my be closed, I think
