### ISSUE TITLE
toList() and ofNullable

### ISSUE THREAD

**Issue by akonior** [aNNiMON/Lightweight-Stream-API#90]
I thought about two enhancements 
1. `.collect(Collectors.toList());` - this is so common that maybe adding dedicated method would be justifiable I mean `stream.toList()` instead of `stream..collect(Collectors.toList());`
2. New method `Stream.ofNullable()`

// PS. This project is awesome. Our Android project codebase looks much cleaner now.

**Comment by aNNiMON** [comment]
Thank you, @akonior. `Stream.toList()` is really convenient shortcut, I'll implement both methods soon.
