### ISSUE TITLE
How does it compare to the Stream API provided in AbacusUtil 

### ISSUE THREAD

**Issue by lihy70** [aNNiMON/Lightweight-Stream-API#92]
Here is link:
https://github.com/landawn/AbacusUtil
http://landawn.com/api-docs/index.html

**Comment by aNNiMON** [comment]
Powerful library, but poorly documented. And seems like it has parallel streams support and extended primitive support (`ByteStream`, `CharStream`, etc).
My project intended to be lightweight. 211 KB vs 5.3 MB
