### ISSUE TITLE
Add takeUntil operator

### ISSUE THREAD

**Issue by dalewking** [aNNiMON/Lightweight-Stream-API#97]
Like this rxjava operator: http://reactivex.io/RxJava/javadoc/rx/Observable.html#takeUntil(rx.Observable)

**UPDATE**

I meant this method: http://reactivex.io/RxJava/javadoc/rx/Observable.html#takeUntil(rx.functions.Func1)

**Comment by aNNiMON** [comment]
I think, it is impossible in Stream API. In rxjava we can compare items in two Observables according to the emit time, but in Stream API there is no time. If two Streams has items, we can take them at any time.

**Comment by dalewking** [comment]
Sorry, linked to the wrong takeUntil method. This is more a variation on takeWhile:

http://reactivex.io/RxJava/javadoc/rx/Observable.html#takeUntil(rx.functions.Func1)

**Comment by dalewking** [comment]
Haven't tested it but I think this would be a working implementation.

    public Stream<T> takeUntil(final Predicate<? super T> predicate) {
        return new Stream<T>(new LsaExtIterator<T>() {

            @Override
            protected void nextIteration() {
                hasNext = iterator.hasNext() && !(isInit && predicate.test(next));
                next = iterator.next();
            }
        });
    }

**Comment by dalewking** [comment]
So as an example:

    IntStream.range(0, 10).takeUntil(x -> x >3)

Would be a stream with 0, 1, 2, 3, 4

**Comment by aNNiMON** [comment]
@dalewking ok, this possible.  Thanks!

**Comment by dalewking** [comment]
Refactored version:

    public Stream<T> takeUntil(final Predicate<? super T> predicate) {
        return new Stream<T>(new LsaExtIterator<T>() {

            @Override
            protected void nextIteration() {
                hasNext = iterator.hasNext() && !(isInit && predicate.test(next));
                next = hasNext ? iterator.next() : null;
            }
        });
    }

**Comment by dalewking** [comment]
Your fix does not release the reference to the last item emitted when it is no longer needed.

The null part of this:

    next = hasNext ? iterator.next() : null;

**Comment by aNNiMON** [comment]
That's my fault. Thank you so much!
